export default {
  FIRST_NAME_REQUIRED: "First name is a required field",
  LAST_NAME_REQUIRED: "Last name is a required field",
  NICKNAME_REQUIRED: "Nickname is a required field",
  LAST_NAME_MIN_LENGTH: "Last name should be at least 3 characters",
  FIRST_NAME_MIN_LENGTH: "First name should be at least 3 characters",
  NICKNAME_MIN_LENGTH: "Nickname should be at least 3 characters",
  BIO_MIN_LENGTH: "Bio should be at least 3 characters",
  DUPLICATE_NICKNAME: "This nickname already exists!",
  INVALID_EMAIL: "The provided email is invalid",
  DUPLICATE_EMAIL: "This email already exists!",
  PASSWORD_REQUIRED: "Password is a required field",
  INVALID_CREDENTIALS: "Invalid email address or password!",
  PASSWORD_MIN_LENGTH: "Password must be at least 8 characters",
  PASSWORD_UPPERCASE: "Password must contain at least one uppercase letter",
  PASSWORD_LOWERCASE: "Password must contain at least one lowercase letter",
  PASSWORD_NUMBER: "Password must contain at least one number",
  PASSWORD_SPECIAL_CHAR: "Password must contain at least one special character",
  USER_NOT_FOUND: "User not found",
  USER_NOT_AUTHORIZED: "User not authorized",
  SESSION_NOT_FOUND: "Session not found",
  ENV_VARIABLES_NOT_EXTRACTED:
    "Environment variables were not extracted properly!",
  MISSING_TOKEN: "No token provided, authentication failed.",
  INVALID_ID: "The ID provided is invalid",
  MISSING_REQ_BODY: "Request body is missing or empty.",
  ENV_VARS_MISSING: "Environment variable were not extracted",
  NO_TOKEN_PROVIDED: "No token provided, authentication failed.",
  TOKEN_HAS_EXPIRED: "Token has expired",
  MISSING_ROLE:
    "You do not have the specified role to interact with this feature",
  // book
  TITLE_REQUIRED: "Title is a required field",
  AUTHOR_REQUIRED: "Author name is required",
  BOOK_ALREADY_ASSIGNED: "You already have this book to your collection",
  MIN_RATING: "Rating must be at least 1",
  MAX_RATING: "Rating must be at most 5",
  DESC_TOO_SHORT: "Description must be at least 10 characters",
  BOOK_NOT_FOUND: "Book with the provided ID was not found",
  BOOK_ALREADY_EXISTS: "Book already exists",
  INVALID_ISBN_FORMAT:
    "Invalid ISBN format. Must be either a valid ISBN-10 or ISBN-13.",
  BOOK_NOT_FOUND_IN_OUR_LIBRARY:
    "The provided book data could not be found in our library",
  BOOK_NOT_ADDED: "There was an issue adding the book to the collection",
};
