apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: docker.io/kostandins/book-tracker-microservices-user-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: prod
            - name: PORT
              value: "3002"
            - name: DATABASE_URL
              value: postgresql://postgres.juiqpttgxazecbcliibr:6m2QBHnQpmwpZMb9@aws-0-eu-central-1.pooler.supabase.com:5432/postgres?schema=user_service
            - name: JWT_SECRET
              value: fell-in-love-with-an-alien
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: QUEUE_USER_DELETED
              value: user_deleted_queue
