apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: docker.io/kostandins/book-tracker-microservices-api-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: prod
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              value: fell-in-love-with-an-alien
            - name: AUTH_SERVICE_URL
              value: http://auth-service:3001
            - name: USER_SERVICE_URL
              value: http://user-service:3002
            - name: BOOK_SERVICE_URL
              value: http://book-service:3003
            - name: USER_BOOKS_SERVICE_URL
              value: http://user-books-service:3004
