apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-books-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-books-service
  template:
    metadata:
      labels:
        app: user-books-service
    spec:
      containers:
        - name: user-books-service
          image: docker.io/kostandins/book-tracker-microservices-user-books-service:dev
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              value: dev
            - name: PORT
              value: "3004"
